### ISSUE TITLE
Add questions on containers (Docker, Nomad, k8s, ...)

### ISSUE THREAD

**Issue by bregman-arie** [bregman-arie/devops-exercises#3]

**Comment by sk3pp3r** [comment]
1. What is Docker?
2. What are the advantages of using Docker container?
3. What are the important features of Docker?
4. What are the main drawbacks of Docker?
5. What is Docker image?
6. What is Docker Engine?
7. Explain Registries
8. What command should you run to see all running container in Docker?
9. Write the command to stop the docker container
10. What is the command to run the image as a container?
11. What are the common instruction in Dockerfile?
12. What is memory-swap flag?
13. Explain Docker Swarm?
14. How can you monitor the docker in production environments?
15. What the states of Docker container?
16. What is Docker hub?
17. What is Virtualization?
18. What is Hypervisor?
19. Explain Docker object labels
20. Write a Docker file to create and copy a directory and built it using python modules?
21. Where the docker volumes are stored?
23. How does communication happen between Docker client and Docker Daemon?
24. Explain Implementation method of Continuous Integration(CI) and Continues Development (CD) in Docker?
25. What are the command to control Docker with Systemd?
26. How to use JSON instead of YAML compose file?
27. What is the command you need to give to push the new image to Docker registry?
28. How to include code with copy/add or volumes?
29. Explain the process of scaling your Docker containers
30. What is the method for creating a Docker container?
31. What are the steps for the Docker container life cycle?
32. How can you run multiple containers using a single service?
33. What is CNM?
34. Does Docker offer support for IPV6?
35. Can you lose data when the container exits?
36. What are a different kind of volume mount types available in Docker?
36. What are a different kind of volume mount types available in Docker?
38. Explain Docker Trusted Registry?
39. What are Docker Namespaces?
40. What are the three components of Docker Architecture
41. What is client?
42. What is the purpose of Docker_Host?
43. How do I run multiple copies of Compose file on the same host?

**Comment by bregman-arie** [comment]
Thanks but I don't copy content and it seems these questions are from:

https://www.guru99.com/docker-interview-questions.html

**Comment by surister** [comment]
Also this doesn't seem like the correct format to issue a PR :P, check the contributing MD

**Comment by MaximeAiguier** [comment]
Thanks !

**Comment by MaximeAiguier** [comment]
Thanks !

**Comment by bregman-arie** [comment]
I think we have enough questions at this point. Thanks, everyone :)
