### ISSUE TITLE
Question/Suggestion : Link different resources for answers

### ISSUE THREAD

**Issue by sagespidy** [bregman-arie/devops-exercises#57]
You guys have done a great job collecting questions. But the answers are lacking.  There are already resources with great explanations. I don't want to copy their hard worked content .
How about we link blogs/articles as answers  here ?
What do you guys think ?

@bregman-arie @surister

**Comment by bregman-arie** [comment]
I think you are right. While surister is doing great job with his answers, I usually provide more concise, summaried version. It's better to link to good resources if possible.

**Comment by sagespidy** [comment]
I am currently preparing for an interview. Have some great links bookmarked. Will start adding links here

**Comment by surister** [comment]
Wouldn't be cool to have 1 question -> 1 external link, that'd feel like we are just googling for people, my python answers are somewhat extensive but they are about topics that you could write books about and showing good knowledege in the interview is a great plus.

 I might be biased since I'm a software developer and I'm passionate about coding.

 I feel like the best way to answer these repo question is the way arie does. It's also true that we lack lots of answer, but, you don't get what this project aims to do in an overnight, it takes time and pr's.

**Comment by surister** [comment]
Also you don't have to copy anyone's content, take a question and answer it as if you were in an interview, after that maybe if you feel it's incomplete, check those resources and complete it as you see fit.

**Comment by sagespidy** [comment]
@surister  I get what you are trying to say. 

My point is this : question collected here are great in quality.
- we don't want to copy somebody's content and paste it here. 
- To answer the questions here  with examples with original content is quite a herculean task and in my honest opinion  is like re-inventing the wheel. Somebody has already explained those concepts in great detail.
- If we add links, this repo could serve as single stop to prepare for interview. Along with  great question we have answers as well.

This is my opinion  only. @bregman-arie @surister  You guys are Maintainers and should discuss among yourselves what is best for the project  and decide on how we should proceed.

Thanks

**Comment by surister** [comment]
I'm my opinion it's far from being an herculean task since most of the answers are answered with 1-3 lines, it's a matter of time although I understand where you com from.
